### ISSUE TITLE
Full screen and console

### ISSUE THREAD

**Issue by AndreaCrotti** [nyergler/hieroglyph#10]
I'm using the default theme with hieroglyph which generates some very nice web pages.

The problem is that I haven't found any way to enable the full screen
(with firefox), and also reading the documentation "c" should give me
a console, but it doesn't do anything on my machine and I don't find
the javascript code that should do this..

Is the documentation still updated about these things?
Thanks,
Andrea

**Comment by yves-chevallier** [comment]
Any news about this issue ? I am also looking to display the slides full screen
