### ISSUE TITLE
custom.css can't override pygments.css

### ISSUE THREAD

**Issue by ecbftw** [nyergler/hieroglyph#107]
I was looking to change the color of the pygments highlight section.  The HTML code is generated as:

> ...
> code line not highlighted
> &lt;span class="hll"> code line highlighted
> &lt;/span>
> ...

I tried to change the `background-color` in the `hll` class using my custom.css, but it wasn't working.  Then I realized the pygments.css is included in the header after the custom.css:

>    ...
>    &lt;link rel="stylesheet" href="_static/custom.css" type="text/css" />
> 
>    &lt;link rel="stylesheet" href="_static/pygments.css" type="text/css" />
> ...

Could you ensure custom.css always comes last?  Would these things a lot easier.

**Comment by nyergler** [comment]
Makes sense. I'd be happy to review a pull request that makes that change. 






On Wed, Sep 30, 2015 at 9:40 AM -0700, "ecbftw" <notifications@github.com> wrote:












I was looking to change the color of the pygments highlight section.  The HTML code is generated as:




...

code line not highlighted

<span class="hll"> code line highlighted

</span>

...




I tried to change the background-color in the hll class using my custom.css, but it wasn't working.  Then I realized the pygments.css is included in the header after the custom.css:




...

   <link rel="stylesheet" href="_static/custom.css" type="text/css" />



<link rel="stylesheet" href="_static/pygments.css" type="text/css" />

...




Could you ensure custom.css always comes last?  Would these things a lot easier.

**Comment by ecbftw** [comment]
Pretty straight forward... see if this works.

**Comment by nyergler** [comment]
Looks like this was fixed in 2015; closing the issue.
