### ISSUE TITLE
custom_css only copied on initial build

### ISSUE THREAD

**Issue by mhelmer** [nyergler/hieroglyph#115]
If I add a `custom_css` and run `make slides`, everything is fine. However, if I update my `custom_css` file, it is not updated when I run `make slides` again. Instead, I have to run `make clean && make slides`. At least for me, it makes it a bit painful to customize the styling. Is this a general sphinx issue or is it something that can be fixed for hieoroglyph?

**Comment by AlbertMietus** [comment]
This is common in sphinx. Al least I see the same both in Sphinx and hieroglyph

Make clean is not needed however, just remove 1 file (eg index.html). It's a workaround but it works for me

--albert
An iPhone is great, but for typing mail
