### ISSUE TITLE
Slides2 always goes to last slide on page load

### ISSUE THREAD

**Issue by avylove** [nyergler/hieroglyph#117]
Loading a page such as index.html results in a redirect to index.html#20, where 20 would be the end slide. I'm assuming this is something in the Javascript, but I can't find it.

The expected behavior would be for it to go to index.html#1

**Comment by nyergler** [comment]
Thanks for taking the time to report this, @avylove.  This was actually fixed since the last release with #95. You can install the development version to get the fix. Apologies for the confusion!
