### ISSUE TITLE
Incompatibility with Sphinx 1.6

### ISSUE THREAD

**Issue by pchampin** [nyergler/hieroglyph#127]
After a ``pip install Sphinx --update``, I can not build my Hieroglyph project anymore.

Hieroglyph version is 0.7.1 . No version of Sphinx >=1.6 works. The log file is attached.

[sphinx-err-mflhksaa.log.txt](https://github.com/nyergler/hieroglyph/files/1169072/sphinx-err-mflhksaa.log.txt)

**Comment by bilderbuchi** [comment]
See also #124. It would be great to get development of this going, as it seems to have stalled pretty hard. Unfortunately, I don't have the skills for that. 
Maybe some Sphinx devs would be interested to lend a hand, to at least keep compatibility with current sphinx?

**Comment by nyergler** [comment]
This should be fixed with https://github.com/nyergler/hieroglyph/pull/129

**Comment by nyergler** [comment]
@pchampin Thanks for double checking things. I was using #120 to track the quickstart issue. I'll see how difficult it will be to make `slide_link_html_sections_to_slides` work with 1.6.

**Comment by nyergler** [comment]
Both issues should be fixed now, @pchampin
