### ISSUE TITLE
'module' object has no attribute 'DEFAULT_VALUE'

### ISSUE THREAD

**Issue by pop** [nyergler/hieroglyph#134]
When I try running `hieroglyph-quickstart` this output:

```
# hieroglyph-quickstart
Traceback (most recent call last):
  File "/usr/bin/hieroglyph-quickstart", line 11, in <module>
    load_entry_point('hieroglyph==1.0.0+3.g1ef062f', 'console_scripts', 'hieroglyph-quickstart')()
  File "/usr/lib/python2.7/site-packages/hieroglyph/quickstart.py", line 87, in quickstart
    d = sphinx.quickstart.DEFAULT_VALUE.copy()
AttributeError: 'module' object has no attribute 'DEFAULT_VALUE'
```

This is the case on NixOS Linux, Alpine Linux, and Ubuntu (the last two were run in Docker containers on NixOS).

For fun did a some light reading with `grep` and found this:

```
✔ ~/src/github.com/nyergler/hieroglyph [hieroglyph-1.0.0|✔] 
20:09 $ git grep DEFAULT_VALUE
src/hieroglyph/quickstart.py:    d = sphinx.quickstart.DEFAULT_VALUE.copy()
```
The line in question calls the DEFAULT_VALUE method in `src/hieroglyph/quickstart.py`.

When we search for that method in the sphinx codebase we get:
```
✔ ~/src/github.com/sphinx/sphinx [v1.7.1|✔] 
20:09 $ git grep DEFAULT_VALUE
```

Nothing meaning that string does not does not exist in the sphinx codebase.

It seems like this has already been documented in #120 (and other issues) and that the fix is to pin an older version of Sphinx, but I wanted to document this specific issue.

Here is some debug info from the Ubuntu container:

```
# hieroglyph --version
1.0.0
# python --version
Python 2.7.13
# pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
# pip freeze
# pip freeze
alabaster==0.7.10
Babel==2.5.3
certifi==2018.1.18
chardet==3.0.4
cryptography==1.7.1
docutils==0.14
enum34==1.1.6
hieroglyph==1.0.0
idna==2.6
imagesize==1.0.0
ipaddress==1.0.17
Jinja2==2.10
keyring==10.1
keyrings.alt==1.3
MarkupSafe==1.0
packaging==16.8
pyasn1==0.1.9
pycrypto==2.6.1
Pygments==2.2.0
pygobject==3.22.0
pyparsing==2.2.0
pytz==2018.3
pyxdg==0.25
requests==2.18.4
SecretStorage==2.3.1
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.7.1
sphinxcontrib-websupport==1.0.1
typing==3.6.4
urllib3==1.22
```

**Comment by pop** [comment]
I can confirm `pip install sphinx==1.5.6` makes `hieroglyph-quickstart` work successfully.

**Comment by pvcraven** [comment]
Also getting this on Windows. Thanks for the work-around.

**Comment by gplanansky** [comment]
Fwiw here are quickstart.py files for sphinx 1.6.7 and 1.8.5 that work for python 3.7.  Note that in sphinx 1.85 sphinx.quickstart becomes sphinx.cmd.quickstart, and do_prompt(...) changes a bit.
For parsimony these just handle the slide_theme  and extensions hieroglyph value, leaving the rest up to the vanilla sphinx quickstart call.   Needed is a tweaked sphinx/templates/quickstart/conf.py_t with "slide_theme = u'{{ slide_theme }}'" added, put into hieroglyph/templates/conf.py_t .

[quickstart-sphinx185.py.txt](https://github.com/nyergler/hieroglyph/files/3072618/quickstart-sphinx185.py.txt)
[quickstart-sphinx167.py.txt](https://github.com/nyergler/hieroglyph/files/3072622/quickstart-sphinx167.py.txt)
