### ISSUE TITLE
Update http://hieroglyph.io/ to contain Release 1.0 docs

### ISSUE THREAD

**Issue by jodygarnett** [nyergler/hieroglyph#144]
Quick request, I would like to share http://hieroglyph.io/ with my team members, but the website PDF downloads as: Release 0.8.dev0 documentation

Can I ask that http://hieroglyph.io/ be configured for the recent Release 1.0 please.

**Comment by nyergler** [comment]
It's a little embarrassing how long this issue was open, but I've:

* updated hieroglyph.io
* configured the github integration to keep it up to date automatically going forward

Thanks for reporting.
