### ISSUE TITLE
Can hieroglyph be parallel safe?

### ISSUE THREAD

**Issue by jodygarnett** [nyergler/hieroglyph#154]
I was looking at enabling `-j auto` on my sphinx-build and hieroglyph produces a warning:

```
WARNING: the hieroglyph extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```
Is it possible to enable parallel read and write in the setup function?

**Comment by nyergler** [comment]
Yup, I believe it can! Fixed on master.
