### ISSUE TITLE
Hieroglyph incompatible with Sphinx 2.x

### ISSUE THREAD

**Issue by craigmaloney** [nyergler/hieroglyph#155]
When installing hieroglyph it did not pin the package of Sphinx that it is compatible with. It installed the latest version of Sphinx (which is at 2.0.1), which has changed the location of the sphinx.quickstart package that hieroglyph uses.

I manually installed Sphinx 1.8 and that cleared up the issue.

May need to pin the version of Sphinx used by hieroglyph or update the import to match the newer versions.

Thanks!

**Comment by lpirl** [comment]
FYI, PR #149 (which is merged into [lpirl/hieroglyph](https://github.com/lpirl/hieroglyph) BTW) also tackles this issue.

**Comment by craigmaloney** [comment]
Can confirm that helped with the installation. Thanks!

**Comment by rawbertp** [comment]
Would be great though, if there was a more recent version of Hieroglyph that supports the latest version of Sphinx. Unfortunately, this project appears to be dead?!

**Comment by lpirl** [comment]
Well, Sphinx apparently changed the API quite a bit, so it's work.
I am sure everyone would be happy to see a PR making Hieroglyph compatible with recent Sphinx APIs.

**Comment by nyergler** [comment]
I believe this has been remedied on the master branch. Can you confirm, @craigmaloney ?

**Comment by craigmaloney** [comment]
Looks like this is fixed. Thank you!

**Comment by pchampin** [comment]
Working for me as well. 

With a minor problem, though: `slide_link_html_sections_to_slides` does not seem to work.

Sill, great work, and thanks. I've been waiting so long for hieroglyph to be compatible with recent versions of Sphinx!

**Comment by nyergler** [comment]
@pchampin That's not entirely surprising; I think Sphinx made some big internal changes since 1.7. 

I'd like to close this out, would you mind making a new issue for the `slide_link_html_sections_to_slides` issue with your observations?

Thanks!

**Comment by nyergler** [comment]
Actually, @pchampin, looks like this is already tracked in #133.

If you have any more details, please add them there!
