### ISSUE TITLE
Unable to access the documentation, "docs.hieroglyph.io may be for sale"

### ISSUE THREAD

**Issue by petarmaric** [nyergler/hieroglyph#167]
It seems that the domain registration for hieroglyph.io has expired :/

**Comment by nyergler** [comment]
I'm seeing what I can do to recover the domain; in the meantime, I've updated the project description. The docs are available at https://hieroglyph.readthedocs.io/en/latest/.

**Comment by kinow** [comment]
Came here to report the same issue. I found the broken link from PYPI :+1: 

I think it'd be best to remove the link from the `README.md`, and link to the RTD link above instead. That would avoid some further confusion for users.
