### ISSUE TITLE
html to slides links not working for `slides2` theme

### ISSUE THREAD

**Issue by jayhesselberth** [nyergler/hieroglyph#78]
Currently the links pointing from HTML to slides in the `slides2` theme only take you to the first slide, because ``slides2`` accepts the slide number, not the slide name.

`slides`
http://dot.com/page.html#header

`slides2`
http://dot.com/page.html#1

**Comment by nyergler** [comment]
I was trying to avoid modifying the underlying HTML/JS too much with `slides2`, but I think I'm going to have to shim in the named hash support. Keeping track of slide numbering when building HTML is going to be pretty rough (given `nextslide`, `slide`, etc).

**Comment by nyergler** [comment]
Thanks again for reporting the issue; this should be fixed in `master` now.
