### ISSUE TITLE
Build failure with Sphinx 1.3 (upcoming release)

### ISSUE THREAD

**Issue by birkenfeld** [nyergler/hieroglyph#84]
From https://github.com/sphinx-doc/sphinx/issues/1662: there is a TypeError when generating slides with hieroglyph under Sphinx 1.3b2.

The problem lies in the `slide_context` function returning the context object. In Sphinx 1.2, the `html-page-context` event had no return value, so the return value was ignored. In Sphinx 1.3, the return value has a meaning: it overrides the template name. But for that it must be a string, not a dictionary.

**Comment by birkenfeld** [comment]
Note, this analysis refers to the latest released version 0.6.5. I just had a look at the code and the event now is connected to a different function, but still has a return value that would be misinterpreted by Sphinx.

**Comment by nyergler** [comment]
Thanks for relaying this, Georg!

I'll take a look ASAP.

**Comment by nyergler** [comment]
It looks like the function linked to `html-page-context` on `master` no longer has a return value.

https://github.com/nyergler/hieroglyph/blob/master/src/hieroglyph/html.py#L104

I was unable to reproduce this with Sphinx 1.3b2 and Hieroglyph master.
